[package]
name = "dimension"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
tilemap = { path = "../tilemap" }
tilemap_shared = { path = "../tilemap_shared" }

bevy = { workspace = true }
# UNUSED (cargo-machete): debug_unwraps = { workspace = true }
# UNUSED (cargo-machete): serde = { workspace = true }
bevy_common_assets = { workspace = true }
bevy_replicon = { workspace = true }
# UNUSED (cargo-machete): bevy_replicon_renet = { workspace = true }
bevy_asset_loader = { workspace = true }
# UNUSED (cargo-machete): delegate = { workspace = true }
# UNUSED (cargo-machete): tracing = { workspace = true }
# UNUSED (cargo-machete): tracing-subscriber = { workspace = true }
