[workspace]
members = ["crates/*"]
resolver = "2"

[package]
name = "argentum_coop"
version = "0.1.0"
edition = "2024"

[features]
default = []

[workspace.dependencies]
bevy = { version = "0.18.1", features = [
    "dynamic_linking",
    "track_location",
    "serialize",
    "jpeg",
] }

strum = "0.28.0"
strum_macros = "0.28.0"
#vec-collections = "0.4.3"
debug_unwraps = "0.1.0"
nano-id = "0.4.0"
rand = "0.10.1"
rand_distr = "0.6.0"
rand_seeder = "*"
rand_pcg = "*"

bevy_ecs_tilemap = { path = "aother/tmap", features = ["serde"] }
bevy_ui_text_input = { git = "https://github.com/Elekrisk/bevy_ui_text_input/", branch = "bevy-0.18" }
bevy_replicon = "0.40.4"
bevy_replicon_renet = "0.16"
bevy_common_assets = { version = "0.16.0", features = ["ron"]}
bevy_spritesheet_animation = "6.1.0"
bevy_asset_loader = { version = "0.26.0", features = ["standard_dynamic_assets"] }
bevy-inspector-egui = "0.36.0"
bevy_enhanced_input = "0.24"
paste = "1.0"
smallvec = "1.15.1"
smallset = "0.1.1"
inventory = "0.3"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ron = "0.12.1"
anyhow = "1.0.102"
splines = { version = "5.0.0", features = ["serde"] }
indexmap = "2.14.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
bevy-fps-counter = "0.9.0"
bitvec = "1.0.1"
delegate = "0.13.5"
bevy_kira_audio = { version = "0.25.0", features = ["wav"] }

noiz = "0.4.0"
avian2d = "0.6.1"
#bevy_save = "1.0.0"
#bevy_rand = "0.11.1"
bevy_northstar = "0.6.2"
superstate = { path = "crates/Superstate" }
bevy_lit = { git = "https://github.com/csandven/bevy_lit" }

#cargo upgrade --incompatible

[dependencies]

multiplayer_shared = { path = "crates/multiplayer_shared" }
common = { path = "crates/acommon" }
common_systems = { path = "crates/acommon_systems" }
asset_loading = { path = "crates/asset_loading" }
game_common = { path = "crates/agame_common" }
debug = { path = "crates/debug" }
host = { path = "crates/host" }
client = { path = "crates/client" }
tilemap = { path = "crates/tilemap" }
regioning = { path = "crates/regioning" }
tilemap_shared = { path = "crates/tilemap_shared" }
modifier_shared = { path = "crates/modifier_shared" }
modifier_systems = { path = "crates/modifier_systems" }
game = { path = "crates/game" }
wildlife = { path = "crates/wildlife" }
movement = { path = "crates/movement" }
being = { path = "crates/being" }
camera = { path = "crates/camera" }
dimension = { path = "crates/dimension" }
#sprite_animation_shared = { path = "crates/sprite_animation_shared" }
#sprite_shared = { path = "crates/sprite_shared" }
sprite_animation = { path = "crates/sprite_animation" }
sprite_systems = { path = "crates/sprite" }
faction = { path = "crates/faction" }
player = { path = "crates/player" }
ac_input = { path = "crates/ac_input" }
ac_audio = { path = "crates/ac_audio" }
time = { path = "crates/time" }
color_sampler = { path = "crates/color_sampler" }
shader = { path = "crates/shader" }
ui_shared = { path = "crates/ui_shared" }
pregame_screen = { path = "crates/pregame_screen" }
setup_screen = { path = "crates/setup_screen" }
item_systems = { path = "crates/item_systems" }
item_shared = { path = "crates/item_shared" }
#param_sets = { path = "crates/param_sets" }

bevy = { workspace = true }
bevy_enhanced_input = { workspace = true }
bevy-inspector-egui = { workspace = true }
tracing = { workspace = true }
#tracing-subscriber = { workspace = true }
avian2d = { workspace = true }
ron.workspace = true
bevy_kira_audio = { workspace = true }

#log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] } # Improve Runtime Performance (Optional)
#bevy_northstar = "0.3.1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
debug = 0
opt-level = 3
strip = "debuginfo"

[profile.release]
opt-level = 3
debug = 0
strip = "debuginfo"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
