use bevy::prelude::*;
use game_common::game_common::ModifierSystems;
use game_common::game_common_components::HealthDamage;
use item_systems::generate_items_on_deaths;
use {
    crate::modifier_hp_systems::*,
    crate::modifier_manip_systems::*,
    crate::modifier_systems::*,
    bevy::time::common_conditions::on_timer,
    bevy_replicon::prelude::*,
    modifier_shared::{
        modifier_components::*,
        modifier_item_types::*,
        modifier_tool_types::*,
        modifier_types::*,
    },
    std::time::Duration,
};

pub fn plugin(app: &mut App) {
    app.add_systems(
        FixedUpdate,
        (
            materialize_modifier_synergies,
            update_modifier_effective_values.run_if(on_timer(Duration::from_millis(200))),
            sync_modifier_name_to_effects,
        )
            .chain()
            .in_set(ModifierSystems),
    )
    .add_systems(
        Update,
        (
            apply_health_damage.run_if(on_message::<HealthDamage>),
            update_body_manipulation_totals,
            (
                mark_dead_by_health.after(apply_health_damage),
                generate_items_on_deaths,
                despawn_entities_on_death,
            )
                .chain(),
        )
            .in_set(ModifierSystems),
    )
    .register_type::<AppliedModifiers>()
    .register_type::<ModifierTarget>()

    .replicate::<ModifierTarget>()
    .replicate::<BaseValue>()
    .replicate::<CurrEffectiveValue>() //NO SÉ SI ES TEMPORAL O NO
    .replicate::<MitigatingOnly>()
    .replicate::<ApplyMode>()
    .replicate::<WalkSpeed>()
    .replicate::<SwimSpeed>()
    .replicate::<FlySpeed>()
    .replicate::<InvertMovement>()
    .replicate::<HitpointsCapacity>()
    .replicate::<HitpointRegenRate>()
    .replicate::<BloodCapacity>()
    .replicate::<Consciousness>()
    .replicate::<PainSensitivity>()
    .replicate::<PainInfliction>()
    .replicate::<PainSlowdown>()
    .replicate::<ManipulationDexterity>()
    .replicate::<ManipulationStrength>()
    .replicate::<Vision>()
    .replicate::<Antidote>()
    .replicate::<ModifierSynergies>()
    .replicate::<OffsetValForSelf>()
    .replicate::<CopyFracOfOthersIntoSelf>()
    .replicate::<MinForDamage>()
    .replicate::<ConvertsDamageOnNonPenetration>()
    .replicate::<BleedRate>()
    .replicate::<Tool>()
    .replicate::<DamageBlunt>()
    .replicate::<DamageSharp>()
    .replicate::<DamagePierce>()
    .replicate::<DamageSlash>()
    .replicate::<DamageFire>()
    .replicate::<DamageFrost>()
    .replicate::<DamageLightning>()
    .replicate::<DamageAcid>()
    .replicate::<DamagePoison>()
    .replicate::<DamageArcane>()
    .replicate::<DamageHoly>()
    .replicate::<DamageShadow>()
    .replicate::<DamageTrue>()
    .replicate::<PenetrationBlunt>()
    .replicate::<PenetrationSharp>()
    .replicate::<PenetrationFire>()
    .replicate::<PenetrationFrost>()
    .replicate::<PenetrationLightning>()
    .replicate::<PenetrationAcid>()
    .replicate::<PenetrationArcane>()
    .replicate::<ArmorBypassChance>()
    .replicate::<ArmorShred>()
    .replicate::<SpallChance>()
    .replicate::<SpallDamageMult>()
    .replicate::<FragmentationChance>()
    .replicate::<FragmentCount>()
    .replicate::<MuzzleVelocity>()
    .replicate::<ProjectileMass>()
    .replicate::<ProjectileDrag>()
    .replicate::<ProjectileGravityMult>()
    .replicate::<PenetrationFalloffPerTile>()
    .replicate::<DamageFalloffPerTile>()
    .replicate::<RicochetChance>()
    .replicate::<RicochetMaxAngle>()
    .replicate::<AttackWindup>()
    .replicate::<AttackCooldown>()
    .replicate::<AttackRecovery>()
    .replicate::<MeleeReach>()
    .replicate::<MinRange>()
    .replicate::<MaxRange>()
    .replicate::<Spread>()
    .replicate::<Recoil>()
    .replicate::<Sway>()
    .replicate::<StaggerPower>()
    .replicate::<Knockback>()
    .replicate::<BodypartTargetingPrecision>()
    .replicate::<MassKg>()
    .replicate::<Encumberance>()
    .replicate::<Bulk>()
    .replicate::<Durability>()
    .replicate::<MaxDurability>()
    .replicate::<MarketValue>()
    .replicate::<Warmth>()
    .replicate::<ArmorBlunt>()
    .replicate::<ArmorSharp>()
    .replicate::<ArmorFire>()
    .replicate::<StackLimit>()
    .replicate_filtered::<ChildOf, With<ModifierTarget>>();
}
