[package]
name = "item_systems"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_enhanced_input = { workspace = true }
bevy_replicon = { workspace = true }
serde = { workspace = true }
ac_input = { path = "../ac_input" }
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
being_shared = { path = "../being_shared" }
item_shared = { path = "../item_shared" }
modifier_shared = { path = "../modifier_shared" }
sprite_systems = { path = "../sprite" }
sprite_shared = { path = "../sprite_shared" }
tilemap_shared = { path = "../tilemap_shared" }
param_sets = { path = "../param_sets" }
player = { path = "../player" }
rand = { workspace = true }
