[package]
name = "color_sampler"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
tilemap_shared = { path = "../tilemap_shared" }

bevy = { workspace = true }
bevy_ecs_tilemap = { workspace = true }
bevy_replicon = { workspace = true }

serde = { workspace = true }
# UNUSED (cargo-machete): strum = { workspace = true }
# UNUSED (cargo-machete): strum_macros = { workspace = true }
bevy_common_assets = { workspace = true }
bevy_asset_loader = { workspace = true }
# UNUSED (cargo-machete): indexmap = { workspace = true }
# UNUSED (cargo-machete): delegate = { workspace = true }
# UNUSED (cargo-machete): tracing = { workspace = true }
# UNUSED (cargo-machete): tracing-subscriber = { workspace = true }
rand = { workspace = true }
# UNUSED (cargo-machete): rand_distr = { workspace = true }
# UNUSED (cargo-machete): rand_seeder = { workspace = true }
# UNUSED (cargo-machete): bevy-inspector-egui = { workspace = true }
# UNUSED (cargo-machete): rand_pcg = { workspace = true }
paste = { workspace = true }
