[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
# UNUSED (cargo-machete): movement = { path = "../movement" }
modifier = { path = "../modifier" }
# UNUSED (cargo-machete): player = { path = "../player" }
being = { path = "../being" }
being_shared = { path = "../being_shared" }
camera = { path = "../camera" }
tilemap = { path = "../tilemap" }
tilemap_shared = { path = "../tilemap_shared" }
sprite_shared = { path = "../sprite_shared" }
sprite = { path = "../sprite" }
fnl = { path = "../fnl" }

bevy = { workspace = true }
serde = { workspace = true }
bevy_replicon = { workspace = true }
# UNUSED (cargo-machete): bevy_replicon_renet = { workspace = true }
# UNUSED (cargo-machete): indexmap = { workspace = true }
# UNUSED (cargo-machete): delegate = { workspace = true }
bevy_ecs_tilemap = { workspace = true }
bevy-inspector-egui = { workspace = true }
rand = { workspace = true }
# UNUSED (cargo-machete): rand_distr = { workspace = true }
# UNUSED (cargo-machete): rand_seeder = { workspace = true }
# UNUSED (cargo-machete): rand_pcg = { workspace = true }
# UNUSED (cargo-machete): noiz = { workspace = true }
bevy-fps-counter = { workspace = true }
