[package]
name = "tilemap"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
camera = { path = "../camera" }
#player = { path = "../player" }
fnl ={ path = "../fnl" }
tilemap_shared ={ path = "../tilemap_shared" }
being_shared = { path = "../being_shared" }
sprite_shared = { path = "../sprite_shared" }
sprite_animation_shared = { path = "../sprite_animation_shared" }
sprite_systems = { path = "../sprite" }
color_sampler = { path = "../color_sampler" }
item_shared = { path = "../item_shared" }

bevy = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
#tracing = { workspace = true }
#tracing-subscriber = { workspace = true }
bevy_replicon = { workspace = true }
bevy_common_assets = { workspace = true }
bevy_asset_loader = { workspace = true }
#strum = { workspace = true }
strum_macros = { workspace = true }
debug_unwraps = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
#rand_seeder = { workspace = true }
rand_pcg = { workspace = true }
#indexmap = { workspace = true }
#delegate = { workspace = true }
bevy_ecs_tilemap = { workspace = true }
bevy-inspector-egui = { workspace = true }
bit-vec = { workspace = true }
paste = { workspace = true }
avian2d = { workspace = true }

noiz = { workspace = true }

#smallvec = { workspace = true }
