[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.17.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license = "MIT"
edition = "2024"
exclude = ["assets/*", "screenshots/*"]

[features]
default = ["render"]
atlas = []
render = []
serde = ["dep:serde", "bevy/serialize"]

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_asset",
    "bevy_sprite_render",
    "bevy_log",
    "morph",
] }
log = "0.4"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
ldtk_rust = { version = "0.6" }
rand = "0.10.1"
serde_json = { version = "1.0" }
tiled = { version = "0.15.0", default-features = false }
thiserror = { version = "2.0" }

[dev-dependencies.bevy]
version = "0.18.1"
default-features = false
features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_asset",
    "png",
    "ktx2",
    "bevy_winit",
    "bevy_window",
    "bevy_text",
    "bevy_sprite",
    "bevy_ui",
    #"file_watcher",
    "multi_threaded",
    "default_font",
    "webgl2",
    "bevy_gizmos",
    "gamepad",
]

[target.'cfg(unix)'.dev-dependencies.bevy]
version = "0.18.1"
default-features = false
features = [
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_asset",
    "png",
    "ktx2",
    "bevy_winit",
    "bevy_window",
    "wayland",
    "x11",
    "bevy_text",
    "bevy_sprite",
    "bevy_ui",
    "multi_threaded",
    "default_font",
    "webgl2",
    "bevy_gizmos",
]
