[package]
name = "movement"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
being_shared = { path = "../being_shared" }
ac_input = { path = "../ac_input" }
modifier_shared = { path = "../modifier_shared" }
sprite_animation_shared = { path = "../sprite_animation_shared" }
#tilemap = { path = "../tilemap" }
tilemap_shared = { path = "../tilemap_shared" }
param_sets = { path = "../param_sets" }

bevy = { workspace = true }
bevy_enhanced_input = { workspace = true }
serde = { workspace = true }
bevy_replicon = { workspace = true }

#avian2d = { workspace = true }
