[package]
name = "sprite_animation_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }

bevy = { workspace = true }
serde = { workspace = true }
bevy_spritesheet_animation = { workspace = true }
bevy_replicon = { workspace = true }
paste = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy_common_assets = { workspace = true }