[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
# UNUSED (cargo-machete): camera = { path = "../camera" }
# UNUSED (cargo-machete): sprite_animation_shared = { path = "../sprite_animation_shared" }
# UNUSED (cargo-machete): sprite = { path = "../sprite" }
# UNUSED (cargo-machete): sprite_shared = { path = "../sprite_shared" }
# UNUSED (cargo-machete): sprite_animation = { path = "../sprite_animation" }
tilemap = { path = "../tilemap" }
tilemap_shared = { path = "../tilemap_shared" }
modifier = { path = "../modifier" }
# UNUSED (cargo-machete): dimension = { path = "../dimension" }
faction = { path = "../faction" }
player = { path = "../player" }
being = { path = "../being" }
being_shared = { path = "../being_shared" }


bevy = { workspace = true }

serde = { workspace = true }
# UNUSED (cargo-machete): strum = { workspace = true }
# UNUSED (cargo-machete): strum_macros = { workspace = true }
# UNUSED (cargo-machete): debug_unwraps = { workspace = true }
rand = { workspace = true }
# UNUSED (cargo-machete): rand_distr = { workspace = true }
# UNUSED (cargo-machete): rand_seeder = { workspace = true }
# UNUSED (cargo-machete): rand_pcg = { workspace = true }
# UNUSED (cargo-machete): bevy_ecs_tilemap = { workspace = true }
# UNUSED (cargo-machete): bevy_simple_scroll_view = { workspace = true }
# UNUSED (cargo-machete): bevy_ui_text_input = { workspace = true }
bevy_replicon = { workspace = true }
# UNUSED (cargo-machete): bevy_replicon_renet = { workspace = true }
bevy_common_assets = { workspace = true }
# UNUSED (cargo-machete): bevy-ui-gradients = { workspace = true }
bevy_asset_loader = { workspace = true }
# UNUSED (cargo-machete): splines = { workspace = true }
# UNUSED (cargo-machete): indexmap = { workspace = true }
# UNUSED (cargo-machete): delegate = { workspace = true }
# UNUSED (cargo-machete): tracing = { workspace = true }
# UNUSED (cargo-machete): tracing-subscriber = { workspace = true }
