[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
# UNUSED (cargo-machete): tracing = { workspace = true }
# UNUSED (cargo-machete): tracing-subscriber = { workspace = true }
bevy_replicon = { workspace = true }
# UNUSED (cargo-machete): bevy_replicon_renet = { workspace = true }

# UNUSED (cargo-machete): strum = { workspace = true }
# UNUSED (cargo-machete): strum_macros = { workspace = true }
# UNUSED (cargo-machete): debug_unwraps = { workspace = true }
rand = { workspace = true }
# UNUSED (cargo-machete): rand_distr = { workspace = true }
# UNUSED (cargo-machete): rand_seeder = { workspace = true }
# UNUSED (cargo-machete): rand_pcg = { workspace = true }
indexmap = { workspace = true }
delegate = { workspace = true }
paste = { workspace = true }
bevy_common_assets = { workspace = true }
bevy_asset_loader = { workspace = true }
bevy-inspector-egui = { workspace = true }
