[package]
name = "modifier_systems"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../acommon" }
game_common = { path = "../agame_common" }
being = { path = "../being" }
being_shared = { path = "../being_shared" }
modifier_shared = { path = "../modifier_shared" }
tilemap = { path = "../tilemap" }
tilemap_shared = { path = "../tilemap_shared" }
item_shared = { path = "../item_shared" }
item_systems = { path = "../item_systems" }

bevy = { workspace = true }
serde = { workspace = true }
bevy_replicon = { workspace = true }
